import { Destination } from "@/lib/types";
import { placeholderGallery } from "@/lib/utils/image";

export const destinations: Destination[] = [
  {
    id: "dest-01",
    slug: "skardu-city",
    name: "Skardu",
    region: "Skardu",
    images: placeholderGallery("skardu-city", 4),
    shortDescription: "Gateway to the Karakoram, ringed by cold desert and turquoise lakes.",
    description:
      "Skardu is the launchpad for most Karakoram expeditions and a destination in its own right — cold desert dunes, the Indus river, and Kharpocho Fort overlooking the town.",
    bestTimeToVisit: "April – October",
    estimatedDuration: "2–3 days",
    activities: ["Sightseeing", "Boating", "Fort visit", "Local cuisine"],
    difficulty: "Easy",
    approxCostPKR: { min: 8000, max: 20000 },
    nearbyHotelIds: ["hotel-01", "hotel-02"],
    nearbyAttractionIds: ["dest-02", "dest-03"],
    lat: 35.2971,
    lng: 75.6333,
    lastUpdated: "2026-08-01",
  },
  {
    id: "dest-02",
    slug: "shangrila-lake",
    name: "Shangrila (Lower Kachura) Lake",
    region: "Skardu",
    images: placeholderGallery("shangrila-lake", 4),
    shortDescription: "The famous 'heaven on earth' lake resort near Skardu.",
    description:
      "A small emerald lake surrounded by orchards, home to the iconic Shangrila Resort with its boat-shaped restaurant.",
    bestTimeToVisit: "May – September",
    estimatedDuration: "Half day",
    activities: ["Boating", "Photography", "Lakeside dining"],
    difficulty: "Easy",
    approxCostPKR: { min: 3000, max: 8000 },
    nearbyHotelIds: ["hotel-02"],
    nearbyAttractionIds: ["dest-01", "dest-04"],
    lat: 35.3861,
    lng: 75.5219,
    lastUpdated: "2026-08-01",
  },
  {
    id: "dest-03",
    slug: "deosai-plains",
    name: "Deosai National Park",
    region: "Skardu",
    images: placeholderGallery("deosai", 4),
    shortDescription: "The 'Land of Giants' — one of the highest plateaus in the world.",
    description:
      "A vast alpine plateau at over 4,000m, carpeted with wildflowers in summer and home to the Himalayan brown bear.",
    bestTimeToVisit: "June – September",
    estimatedDuration: "1–2 days",
    activities: ["Wildlife spotting", "Camping", "Photography", "Trekking"],
    difficulty: "Moderate",
    approxCostPKR: { min: 6000, max: 15000 },
    nearbyHotelIds: ["hotel-02"],
    nearbyAttractionIds: ["dest-01"],
    lat: 34.9500,
    lng: 75.4167,
    lastUpdated: "2026-08-01",
  },
  {
    id: "dest-04",
    slug: "shigar-valley",
    name: "Shigar Valley",
    region: "Shigar",
    images: placeholderGallery("shigar", 4),
    shortDescription: "A green oasis of orchards and the restored Shigar Fort.",
    description:
      "Shigar Valley blends Balti architecture with fertile orchards along the Shigar river, and serves as a base for Baltoro treks.",
    bestTimeToVisit: "April – October",
    estimatedDuration: "1 day",
    activities: ["Heritage walk", "Fort visit", "Local crafts"],
    difficulty: "Easy",
    approxCostPKR: { min: 4000, max: 10000 },
    nearbyHotelIds: ["hotel-03"],
    nearbyAttractionIds: ["dest-01"],
    lat: 35.4225,
    lng: 75.7439,
    lastUpdated: "2026-08-01",
  },
  {
    id: "dest-05",
    slug: "hunza-valley",
    name: "Hunza Valley",
    region: "Hunza",
    images: placeholderGallery("hunza", 4),
    shortDescription: "Snow-capped peaks over terraced fields — GB's most iconic valley.",
    description:
      "Hunza is famed for Rakaposhi views, the Karakoram Highway, apricot orchards, and centuries-old forts at Karimabad and Altit.",
    bestTimeToVisit: "March – November",
    estimatedDuration: "2–4 days",
    activities: ["Fort visits", "Hiking", "Local markets", "Viewpoints"],
    difficulty: "Easy",
    approxCostPKR: { min: 10000, max: 25000 },
    nearbyHotelIds: ["hotel-04", "hotel-05"],
    nearbyAttractionIds: ["dest-06", "dest-07"],
    lat: 36.3167,
    lng: 74.6500,
    lastUpdated: "2026-08-01",
  },
  {
    id: "dest-06",
    slug: "attabad-lake",
    name: "Attabad Lake",
    region: "Hunza",
    images: placeholderGallery("attabad", 4),
    shortDescription: "A striking turquoise lake formed by a 2010 landslide.",
    description:
      "Attabad Lake's electric-blue waters now host boating and jet-skiing against a backdrop of dramatic cliffs along the KKH.",
    bestTimeToVisit: "April – October",
    estimatedDuration: "Half day",
    activities: ["Boating", "Jet skiing", "Photography"],
    difficulty: "Easy",
    approxCostPKR: { min: 3000, max: 7000 },
    nearbyHotelIds: ["hotel-04"],
    nearbyAttractionIds: ["dest-05"],
    lat: 36.3183,
    lng: 74.8697,
    lastUpdated: "2026-08-01",
  },
  {
    id: "dest-07",
    slug: "passu-cones",
    name: "Passu Cones & Glacier",
    region: "Hunza",
    images: placeholderGallery("passu", 4),
    shortDescription: "Jagged cathedral peaks beside the Passu and Batura glaciers.",
    description:
      "The Passu Cones are among the most photographed peaks in GB, reachable via the Hussaini suspension bridge walk.",
    bestTimeToVisit: "April – October",
    estimatedDuration: "1 day",
    activities: ["Suspension bridge walk", "Glacier viewpoint", "Photography"],
    difficulty: "Moderate",
    approxCostPKR: { min: 3000, max: 8000 },
    nearbyHotelIds: ["hotel-05"],
    nearbyAttractionIds: ["dest-05", "dest-06"],
    lat: 36.4667,
    lng: 74.8833,
    lastUpdated: "2026-08-01",
  },
  {
    id: "dest-08",
    slug: "gilgit-city",
    name: "Gilgit",
    region: "Gilgit",
    images: placeholderGallery("gilgit", 4),
    shortDescription: "The regional hub where the Karakoram, Hindukush and Himalaya meet.",
    description:
      "Gilgit is GB's commercial capital, home to the Kargah Buddha rock carving and a base for onward travel to Hunza and Naltar.",
    bestTimeToVisit: "April – October",
    estimatedDuration: "1–2 days",
    activities: ["Bazaar walk", "Kargah Buddha", "Polo ground"],
    difficulty: "Easy",
    approxCostPKR: { min: 5000, max: 12000 },
    nearbyHotelIds: ["hotel-06"],
    nearbyAttractionIds: ["dest-09"],
    lat: 35.9208,
    lng: 74.3144,
    lastUpdated: "2026-08-01",
  },
  {
    id: "dest-09",
    slug: "naltar-valley",
    name: "Naltar Valley",
    region: "Ghizer",
    images: placeholderGallery("naltar", 4),
    shortDescription: "Pine forests and three colour-changing alpine lakes.",
    description:
      "Naltar is known for its ski slopes in winter and the Bashkiri, Satrangi and Blue lakes trio in summer.",
    bestTimeToVisit: "May – September (summer), Jan – Feb (skiing)",
    estimatedDuration: "1 day",
    activities: ["Hiking", "Skiing (winter)", "Lake visits"],
    difficulty: "Moderate",
    approxCostPKR: { min: 6000, max: 14000 },
    nearbyHotelIds: ["hotel-06"],
    nearbyAttractionIds: ["dest-08"],
    lat: 36.1667,
    lng: 74.1833,
    lastUpdated: "2026-08-01",
  },
  {
    id: "dest-10",
    slug: "fairy-meadows",
    name: "Fairy Meadows",
    region: "Diamer",
    images: placeholderGallery("fairy-meadows", 4),
    shortDescription: "Face-to-face views of Nanga Parbat's sheer Rupal face.",
    description:
      "A jeep-and-hike-in meadow beneath Nanga Parbat, considered one of the most dramatic viewpoints in the Himalaya.",
    bestTimeToVisit: "May – September",
    estimatedDuration: "2 days",
    activities: ["Trekking", "Camping", "Photography"],
    difficulty: "Challenging",
    approxCostPKR: { min: 12000, max: 28000 },
    nearbyHotelIds: ["hotel-07"],
    nearbyAttractionIds: [],
    lat: 35.3833,
    lng: 74.5833,
    lastUpdated: "2026-08-01",
  },
  {
    id: "dest-11",
    slug: "rama-lake",
    name: "Rama Lake",
    region: "Astore",
    images: placeholderGallery("rama-lake", 4),
    shortDescription: "A quiet meadow lake beneath Nanga Parbat's northern flank.",
    description:
      "Rama Meadow and its small glacial lake offer a gentler, family-friendly alternative to Fairy Meadows with similar views.",
    bestTimeToVisit: "May – September",
    estimatedDuration: "1 day",
    activities: ["Picnic", "Short hikes", "Photography"],
    difficulty: "Easy",
    approxCostPKR: { min: 5000, max: 12000 },
    nearbyHotelIds: ["hotel-07"],
    nearbyAttractionIds: ["dest-10"],
    lat: 35.3167,
    lng: 74.7,
    lastUpdated: "2026-08-01",
  },
  {
    id: "dest-12",
    slug: "khaplu-valley",
    name: "Khaplu Valley",
    region: "Ghanche",
    images: placeholderGallery("khaplu", 4),
    shortDescription: "A remote valley anchored by the restored Khaplu Palace.",
    description:
      "Khaplu is a quieter alternative to Skardu, centred on the beautifully restored Khaplu Palace (Yabgo House).",
    bestTimeToVisit: "April – October",
    estimatedDuration: "1 day",
    activities: ["Palace visit", "Heritage walk"],
    difficulty: "Easy",
    approxCostPKR: { min: 4000, max: 10000 },
    nearbyHotelIds: ["hotel-08"],
    nearbyAttractionIds: [],
    lat: 35.1667,
    lng: 76.3333,
    lastUpdated: "2026-08-01",
  },
  {
    id: "dest-13",
    slug: "rakaposhi-viewpoint-nagar",
    name: "Rakaposhi Viewpoint (Nagar)",
    region: "Nagar",
    images: placeholderGallery("nagar", 4),
    shortDescription: "The classic front-on view of Rakaposhi from Nagar Valley.",
    description:
      "Nagar Valley faces Hunza across the river and offers arguably the finest unobstructed view of Rakaposhi's full height.",
    bestTimeToVisit: "April – October",
    estimatedDuration: "Half day",
    activities: ["Viewpoint", "Photography", "Short walks"],
    difficulty: "Easy",
    approxCostPKR: { min: 3000, max: 8000 },
    nearbyHotelIds: ["hotel-04"],
    nearbyAttractionIds: ["dest-05"],
    lat: 36.2333,
    lng: 74.7333,
    lastUpdated: "2026-08-01",
  },
  {
    id: "dest-14",
    slug: "kharmang-valley",
    name: "Kharmang Valley",
    region: "Kharmang",
    images: placeholderGallery("kharmang", 4),
    shortDescription: "An off-the-beaten-path valley along the Indus, near the LoC.",
    description:
      "One of GB's least-visited districts, Kharmang offers stark Indus-valley scenery and traditional Balti villages.",
    bestTimeToVisit: "May – September",
    estimatedDuration: "1 day",
    activities: ["Village walks", "Photography"],
    difficulty: "Moderate",
    approxCostPKR: { min: 5000, max: 12000 },
    nearbyHotelIds: [],
    nearbyAttractionIds: ["dest-01"],
    lat: 34.9333,
    lng: 76.1167,
    lastUpdated: "2026-08-01",
  },
];
