import { Mountain } from "@/lib/types";
import { placeholderGallery } from "@/lib/utils/image";

export const mountains: Mountain[] = [
  {
    id: "mtn-01",
    slug: "k2",
    name: "K2",
    heightMeters: 8611,
    range: "Karakoram",
    worldRank: 2,
    difficulty: "Extreme",
    images: placeholderGallery("k2", 3),
    description:
      "The 'Savage Mountain' — the world's second-highest peak and one of the most technically demanding 8,000m climbs, reached via the Baltoro Glacier.",
    nearestTown: "Skardu",
    lat: 35.8825,
    lng: 76.5133,
  },
  {
    id: "mtn-02",
    slug: "nanga-parbat",
    name: "Nanga Parbat",
    heightMeters: 8126,
    range: "Himalaya",
    worldRank: 9,
    difficulty: "Extreme",
    images: placeholderGallery("nanga-parbat", 3),
    description:
      "Known as the 'Killer Mountain,' Nanga Parbat rises dramatically from the Indus valley and is visible from Fairy Meadows.",
    nearestTown: "Chilas",
    lat: 35.2358,
    lng: 74.5892,
  },
  {
    id: "mtn-03",
    slug: "rakaposhi",
    name: "Rakaposhi",
    heightMeters: 7788,
    range: "Karakoram",
    worldRank: 27,
    difficulty: "Challenging",
    images: placeholderGallery("rakaposhi", 3),
    description:
      "Rakaposhi has one of the highest uninterrupted rock-and-ice faces on Earth, towering above Hunza and Nagar valleys.",
    nearestTown: "Hunza",
    lat: 36.1550,
    lng: 74.4897,
  },
  {
    id: "mtn-04",
    slug: "broad-peak",
    name: "Broad Peak",
    heightMeters: 8051,
    range: "Karakoram",
    worldRank: 12,
    difficulty: "Extreme",
    images: placeholderGallery("broad-peak", 3),
    description:
      "Named for its wide summit ridge, Broad Peak sits close to K2 and Gasherbrum along the Baltoro Glacier route.",
    nearestTown: "Skardu",
    lat: 35.8117,
    lng: 76.5683,
  },
  {
    id: "mtn-05",
    slug: "gasherbrum",
    name: "Gasherbrum I & II",
    heightMeters: 8080,
    range: "Karakoram",
    worldRank: 11,
    difficulty: "Extreme",
    images: placeholderGallery("gasherbrum", 3),
    description:
      "The Gasherbrum group ('Shining Wall') forms a striking cluster of peaks deep in the Baltoro region.",
    nearestTown: "Skardu",
    lat: 35.7583,
    lng: 76.6533,
  },
  {
    id: "mtn-06",
    slug: "masherbrum",
    name: "Masherbrum",
    heightMeters: 7821,
    range: "Karakoram",
    worldRank: 22,
    difficulty: "Extreme",
    images: placeholderGallery("masherbrum", 3),
    description:
      "Masherbrum (K1) was the first-named Karakoram giant seen by early surveyors, dominating the skyline above Khaplu and Hushe.",
    nearestTown: "Khaplu",
    lat: 35.6497,
    lng: 76.3067,
  },
];
