import { Hotel } from "@/lib/types";
import { placeholderGallery } from "@/lib/utils/image";

export const hotels: Hotel[] = [
  {
    id: "hotel-01",
    slug: "indus-motel-skardu",
    name: "Indus Motel Skardu",
    city: "Skardu",
    images: placeholderGallery("indus-motel", 3),
    starRating: 3,
    category: "Mid-Range",
    estimatedPricePKR: 12000,
    facilities: ["Free Wi-Fi", "Parking", "Restaurant", "Room Service"],
    rooms: [
      { type: "Standard Double", capacity: 2, estimatedPricePKR: 12000 },
      { type: "Family Room", capacity: 4, estimatedPricePKR: 18000 },
    ],
    cancellationPolicy: "Cancellation policy details will be provided by the hotel at time of booking.",
    lat: 35.2965,
    lng: 75.6301,
    lastUpdated: "2026-08-01",
  },
  {
    id: "hotel-02",
    slug: "shangrila-resort-skardu",
    name: "Shangrila Resort",
    city: "Skardu",
    images: placeholderGallery("shangrila-resort", 3),
    starRating: 4,
    category: "Luxury",
    estimatedPricePKR: 35000,
    facilities: ["Free Wi-Fi", "Lake View", "Restaurant", "Boating", "Parking"],
    rooms: [
      { type: "Deluxe Cottage", capacity: 2, estimatedPricePKR: 35000 },
      { type: "Lake View Suite", capacity: 3, estimatedPricePKR: 48000 },
    ],
    cancellationPolicy: "Cancellation policy details will be provided by the hotel at time of booking.",
    lat: 35.3861,
    lng: 75.5219,
    lastUpdated: "2026-08-01",
  },
  {
    id: "hotel-03",
    slug: "shigar-fort-residence",
    name: "Shigar Fort Residence",
    city: "Shigar",
    images: placeholderGallery("shigar-fort", 3),
    starRating: 4,
    category: "Luxury",
    estimatedPricePKR: 32000,
    facilities: ["Heritage Building", "Free Wi-Fi", "Restaurant", "Garden"],
    rooms: [{ type: "Heritage Room", capacity: 2, estimatedPricePKR: 32000 }],
    cancellationPolicy: "Cancellation policy details will be provided by the hotel at time of booking.",
    lat: 35.4225,
    lng: 75.7439,
    lastUpdated: "2026-08-01",
  },
  {
    id: "hotel-04",
    slug: "hunza-serena-inn",
    name: "Hunza Serena Inn",
    city: "Hunza",
    images: placeholderGallery("hunza-serena", 3),
    starRating: 4,
    category: "Luxury",
    estimatedPricePKR: 30000,
    facilities: ["Mountain View", "Free Wi-Fi", "Restaurant", "Parking"],
    rooms: [
      { type: "Deluxe Room", capacity: 2, estimatedPricePKR: 30000 },
      { type: "Suite", capacity: 3, estimatedPricePKR: 42000 },
    ],
    cancellationPolicy: "Cancellation policy details will be provided by the hotel at time of booking.",
    lat: 36.3167,
    lng: 74.65,
    lastUpdated: "2026-08-01",
  },
  {
    id: "hotel-05",
    slug: "passu-inn",
    name: "Passu Inn",
    city: "Hunza",
    images: placeholderGallery("passu-inn", 3),
    starRating: 3,
    category: "Budget",
    estimatedPricePKR: 7000,
    facilities: ["Free Wi-Fi", "Restaurant", "Glacier View"],
    rooms: [{ type: "Standard Room", capacity: 2, estimatedPricePKR: 7000 }],
    cancellationPolicy: "Cancellation policy details will be provided by the hotel at time of booking.",
    lat: 36.4667,
    lng: 74.8833,
    lastUpdated: "2026-08-01",
  },
  {
    id: "hotel-06",
    slug: "gilgit-riverside-hotel",
    name: "Gilgit Riverside Hotel",
    city: "Gilgit",
    images: placeholderGallery("gilgit-riverside", 3),
    starRating: 3,
    category: "Mid-Range",
    estimatedPricePKR: 10000,
    facilities: ["Free Wi-Fi", "River View", "Restaurant", "Parking"],
    rooms: [{ type: "Standard Double", capacity: 2, estimatedPricePKR: 10000 }],
    cancellationPolicy: "Cancellation policy details will be provided by the hotel at time of booking.",
    lat: 35.9208,
    lng: 74.3144,
    lastUpdated: "2026-08-01",
  },
  {
    id: "hotel-07",
    slug: "raikot-fairy-meadows-cottages",
    name: "Raikot Fairy Meadows Cottages",
    city: "Diamer",
    images: placeholderGallery("raikot-cottages", 3),
    starRating: 3,
    category: "Budget",
    estimatedPricePKR: 8000,
    facilities: ["Nanga Parbat View", "Bonfire", "Meals Included"],
    rooms: [{ type: "Wooden Cottage", capacity: 2, estimatedPricePKR: 8000 }],
    cancellationPolicy: "Cancellation policy details will be provided by the hotel at time of booking.",
    lat: 35.3833,
    lng: 74.5833,
    lastUpdated: "2026-08-01",
  },
  {
    id: "hotel-08",
    slug: "khaplu-palace-residence",
    name: "Khaplu Palace Residence",
    city: "Ghanche",
    images: placeholderGallery("khaplu-palace", 3),
    starRating: 4,
    category: "Luxury",
    estimatedPricePKR: 28000,
    facilities: ["Heritage Building", "Free Wi-Fi", "Restaurant", "Garden"],
    rooms: [{ type: "Palace Room", capacity: 2, estimatedPricePKR: 28000 }],
    cancellationPolicy: "Cancellation policy details will be provided by the hotel at time of booking.",
    lat: 35.1667,
    lng: 76.3333,
    lastUpdated: "2026-08-01",
  },
];
