import { Hotel } from "@/lib/types";
import { placeholderGallery } from "@/lib/utils/image";

export const hotels: Hotel[] = [
  {
    id: "hotel-01",
    slug: "indus-motel-skardu",
    name: "Indus Motel Skardu",
    city: "Skardu",
    images: placeholderGallery("indus-motel", 3),
    starRating: 3,
    category: "Mid-Range",
    estimatedPricePKR: 12000,
    facilities: ["Free Wi-Fi", "Parking", "Restaurant", "Room Service"],
    rooms: [
      {
        type: "Standard Double",
        capacity: 3,
        estimatedPricePKR: 12000,
        images: placeholderGallery("indus-motel-standard-double", 3),
        bedConfig: "1 Queen Bed",
        maxOccupancy: { adults: 2, children: 1 },
        sizeSqFt: 180,
        facilities: ["Air Conditioning", "Attached Bathroom", "Free Wi-Fi", "TV"],
      },
      {
        type: "Family Room",
        capacity: 6,
        estimatedPricePKR: 18000,
        images: placeholderGallery("indus-motel-family-room", 3),
        bedConfig: "2 Double Beds",
        maxOccupancy: { adults: 4, children: 2 },
        sizeSqFt: 280,
        facilities: ["Air Conditioning", "Attached Bathroom", "Free Wi-Fi", "TV", "Extra Bedding"],
      },
    ],
    cancellationPolicy: "Cancellation policy details will be provided by the hotel at time of booking.",
    lat: 35.2965,
    lng: 75.6301,
    lastUpdated: "2026-08-01",
  },
  {
    id: "hotel-02",
    slug: "shangrila-resort-skardu",
    name: "Shangrila Resort",
    city: "Skardu",
    images: placeholderGallery("shangrila-resort", 3),
    starRating: 4,
    category: "Luxury",
    estimatedPricePKR: 35000,
    facilities: ["Free Wi-Fi", "Lake View", "Restaurant", "Boating", "Parking"],
    rooms: [
      {
        type: "Deluxe Cottage",
        capacity: 3,
        estimatedPricePKR: 35000,
        images: placeholderGallery("shangrila-deluxe-cottage", 3),
        bedConfig: "1 King Bed",
        maxOccupancy: { adults: 2, children: 1 },
        sizeSqFt: 320,
        facilities: ["Lake View", "Air Conditioning", "Attached Bathroom", "Mini Fridge", "Free Wi-Fi"],
      },
      {
        type: "Lake View Suite",
        capacity: 5,
        estimatedPricePKR: 48000,
        images: placeholderGallery("shangrila-lake-view-suite", 3),
        bedConfig: "1 King Bed + 1 Sofa Bed",
        maxOccupancy: { adults: 3, children: 2 },
        sizeSqFt: 450,
        facilities: [
          "Lake View",
          "Air Conditioning",
          "Private Balcony",
          "Attached Bathroom",
          "Mini Fridge",
          "Free Wi-Fi",
        ],
      },
    ],
    cancellationPolicy: "Cancellation policy details will be provided by the hotel at time of booking.",
    lat: 35.3861,
    lng: 75.5219,
    lastUpdated: "2026-08-01",
  },
  {
    id: "hotel-03",
    slug: "shigar-fort-residence",
    name: "Shigar Fort Residence",
    city: "Shigar",
    images: placeholderGallery("shigar-fort", 3),
    starRating: 4,
    category: "Luxury",
    estimatedPricePKR: 32000,
    facilities: ["Heritage Building", "Free Wi-Fi", "Restaurant", "Garden"],
    rooms: [
      {
        type: "Heritage Room",
        capacity: 2,
        estimatedPricePKR: 32000,
        images: placeholderGallery("shigar-fort-heritage-room", 3),
        bedConfig: "1 Queen Bed",
        maxOccupancy: { adults: 2, children: 0 },
        sizeSqFt: 240,
        facilities: ["Heritage Decor", "Attached Bathroom", "Garden View", "Free Wi-Fi"],
      },
    ],
    cancellationPolicy: "Cancellation policy details will be provided by the hotel at time of booking.",
    lat: 35.4225,
    lng: 75.7439,
    lastUpdated: "2026-08-01",
  },
  {
    id: "hotel-04",
    slug: "hunza-serena-inn",
    name: "Hunza Serena Inn",
    city: "Hunza",
    images: placeholderGallery("hunza-serena", 3),
    starRating: 4,
    category: "Luxury",
    estimatedPricePKR: 30000,
    facilities: ["Mountain View", "Free Wi-Fi", "Restaurant", "Parking"],
    rooms: [
      {
        type: "Deluxe Room",
        capacity: 3,
        estimatedPricePKR: 30000,
        images: placeholderGallery("hunza-serena-deluxe-room", 3),
        bedConfig: "1 King Bed",
        maxOccupancy: { adults: 2, children: 1 },
        sizeSqFt: 260,
        facilities: ["Mountain View", "Air Conditioning", "Attached Bathroom", "Free Wi-Fi", "TV"],
      },
      {
        type: "Suite",
        capacity: 5,
        estimatedPricePKR: 42000,
        images: placeholderGallery("hunza-serena-suite", 3),
        bedConfig: "1 King Bed + 1 Sofa Bed",
        maxOccupancy: { adults: 3, children: 2 },
        sizeSqFt: 400,
        facilities: ["Mountain View", "Air Conditioning", "Sitting Area", "Attached Bathroom", "Free Wi-Fi", "TV"],
      },
    ],
    cancellationPolicy: "Cancellation policy details will be provided by the hotel at time of booking.",
    lat: 36.3167,
    lng: 74.65,
    lastUpdated: "2026-08-01",
  },
  {
    id: "hotel-05",
    slug: "passu-inn",
    name: "Passu Inn",
    city: "Hunza",
    images: placeholderGallery("passu-inn", 3),
    starRating: 3,
    category: "Budget",
    estimatedPricePKR: 7000,
    facilities: ["Free Wi-Fi", "Restaurant", "Glacier View"],
    rooms: [
      {
        type: "Standard Room",
        capacity: 3,
        estimatedPricePKR: 7000,
        images: placeholderGallery("passu-inn-standard-room", 3),
        bedConfig: "2 Twin Beds",
        maxOccupancy: { adults: 2, children: 1 },
        sizeSqFt: 160,
        facilities: ["Glacier View", "Attached Bathroom", "Free Wi-Fi"],
      },
    ],
    cancellationPolicy: "Cancellation policy details will be provided by the hotel at time of booking.",
    lat: 36.4667,
    lng: 74.8833,
    lastUpdated: "2026-08-01",
  },
  {
    id: "hotel-06",
    slug: "gilgit-riverside-hotel",
    name: "Gilgit Riverside Hotel",
    city: "Gilgit",
    images: placeholderGallery("gilgit-riverside", 3),
    starRating: 3,
    category: "Mid-Range",
    estimatedPricePKR: 10000,
    facilities: ["Free Wi-Fi", "River View", "Restaurant", "Parking"],
    rooms: [
      {
        type: "Standard Double",
        capacity: 3,
        estimatedPricePKR: 10000,
        images: placeholderGallery("gilgit-riverside-standard-double", 3),
        bedConfig: "1 Queen Bed",
        maxOccupancy: { adults: 2, children: 1 },
        sizeSqFt: 190,
        facilities: ["River View", "Air Conditioning", "Attached Bathroom", "Free Wi-Fi", "TV"],
      },
    ],
    cancellationPolicy: "Cancellation policy details will be provided by the hotel at time of booking.",
    lat: 35.9208,
    lng: 74.3144,
    lastUpdated: "2026-08-01",
  },
  {
    id: "hotel-07",
    slug: "raikot-fairy-meadows-cottages",
    name: "Raikot Fairy Meadows Cottages",
    city: "Diamer",
    images: placeholderGallery("raikot-cottages", 3),
    starRating: 3,
    category: "Budget",
    estimatedPricePKR: 8000,
    facilities: ["Nanga Parbat View", "Bonfire", "Meals Included"],
    rooms: [
      {
        type: "Wooden Cottage",
        capacity: 3,
        estimatedPricePKR: 8000,
        images: placeholderGallery("raikot-cottages-wooden-cottage", 3),
        bedConfig: "1 Double Bed",
        maxOccupancy: { adults: 2, children: 1 },
        sizeSqFt: 150,
        facilities: ["Nanga Parbat View", "Shared Bathroom", "Bonfire Access"],
      },
    ],
    cancellationPolicy: "Cancellation policy details will be provided by the hotel at time of booking.",
    lat: 35.3833,
    lng: 74.5833,
    lastUpdated: "2026-08-01",
  },
  {
    id: "hotel-08",
    slug: "khaplu-palace-residence",
    name: "Khaplu Palace Residence",
    city: "Ghanche",
    images: placeholderGallery("khaplu-palace", 3),
    starRating: 4,
    category: "Luxury",
    estimatedPricePKR: 28000,
    facilities: ["Heritage Building", "Free Wi-Fi", "Restaurant", "Garden"],
    rooms: [
      {
        type: "Palace Room",
        capacity: 3,
        estimatedPricePKR: 28000,
        images: placeholderGallery("khaplu-palace-room", 3),
        bedConfig: "1 King Bed",
        maxOccupancy: { adults: 2, children: 1 },
        sizeSqFt: 300,
        facilities: ["Heritage Decor", "Attached Bathroom", "Garden View", "Free Wi-Fi"],
      },
    ],
    cancellationPolicy: "Cancellation policy details will be provided by the hotel at time of booking.",
    lat: 35.1667,
    lng: 76.3333,
    lastUpdated: "2026-08-01",
  },
];
