import { TourPackage } from "@/lib/types";
import { placeholderGallery } from "@/lib/utils/image";

export const packages: TourPackage[] = [
  {
    id: "pkg-01",
    slug: "3-day-skardu-escape",
    title: "3-Day Skardu Quick Escape",
    category: "Family",
    durationDays: 3,
    images: placeholderGallery("pkg-skardu-3day", 4),
    estimatedPricePKR: { min: 28000, max: 45000 },
    highlights: ["Shangrila Lake", "Kharpocho Fort", "Deosai day trip", "Skardu bazaar"],
    itinerary: [
      { day: 1, title: "Arrival in Skardu", description: "Arrive in Skardu, check in, evening walk along the Indus and local bazaar.", overnightAt: "Skardu" },
      { day: 2, title: "Shangrila & Kharpocho Fort", description: "Visit Shangrila Lake in the morning and Kharpocho Fort for sunset views over the city.", overnightAt: "Skardu" },
      { day: 3, title: "Deosai day trip & departure", description: "Early drive to Deosai Plains, return by afternoon for departure.", overnightAt: "—" },
    ],
    included: ["Hotel accommodation", "Private transport", "Breakfast"],
    excluded: ["Airfare", "Lunch & dinner", "Entry tickets"],
    regions: ["Skardu"],
    lastUpdated: "2026-08-01",
  },
  {
    id: "pkg-02",
    slug: "5-day-adventure-trek",
    title: "5-Day Adventure Trek",
    category: "Adventure",
    durationDays: 5,
    images: placeholderGallery("pkg-adventure-5day", 4),
    estimatedPricePKR: { min: 55000, max: 85000 },
    highlights: ["Deosai crossing", "Camping under the stars", "Local guide", "Wildlife spotting"],
    itinerary: [
      { day: 1, title: "Arrival & briefing", description: "Arrive in Skardu, gear check and trek briefing with your guide.", overnightAt: "Skardu" },
      { day: 2, title: "Skardu to Deosai", description: "Drive to Deosai National Park, set up camp near Sheosar Lake.", overnightAt: "Camp, Deosai" },
      { day: 3, title: "Deosai exploration", description: "Full day exploring the plateau on foot, wildlife and wildflower spotting.", overnightAt: "Camp, Deosai" },
      { day: 4, title: "Deosai to Skardu", description: "Trek out and drive back to Skardu, rest and recovery.", overnightAt: "Skardu" },
      { day: 5, title: "Departure", description: "Free morning, transfer for departure.", overnightAt: "—" },
    ],
    included: ["Camping equipment", "Guide & porter", "All meals during trek"],
    excluded: ["Airfare", "Personal gear", "Travel insurance"],
    regions: ["Skardu"],
    lastUpdated: "2026-08-01",
  },
  {
    id: "pkg-03",
    slug: "7-day-skardu-hunza-explorer",
    title: "7-Day Skardu + Hunza Explorer",
    category: "Family",
    durationDays: 7,
    images: placeholderGallery("pkg-skardu-hunza-7day", 4),
    estimatedPricePKR: { min: 95000, max: 140000 },
    highlights: ["Skardu lakes", "Karakoram Highway drive", "Hunza forts", "Attabad Lake", "Passu Cones"],
    itinerary: [
      { day: 1, title: "Arrival in Skardu", description: "Arrive and settle in, short orientation walk.", overnightAt: "Skardu" },
      { day: 2, title: "Skardu sightseeing", description: "Shangrila Lake, Kharpocho Fort, Indus riverside.", overnightAt: "Skardu" },
      { day: 3, title: "Skardu to Hunza", description: "Scenic drive along the Karakoram Highway to Hunza Valley.", overnightAt: "Hunza" },
      { day: 4, title: "Karimabad & Altit Fort", description: "Explore Baltit Fort, Altit Fort and Karimabad bazaar.", overnightAt: "Hunza" },
      { day: 5, title: "Attabad Lake & Passu", description: "Boating at Attabad Lake, walk to Passu Cones viewpoint.", overnightAt: "Hunza" },
      { day: 6, title: "Nagar viewpoint", description: "Visit the Rakaposhi viewpoint in Nagar Valley, free afternoon.", overnightAt: "Hunza" },
      { day: 7, title: "Departure", description: "Drive back towards Gilgit for onward departure.", overnightAt: "—" },
    ],
    included: ["Hotel accommodation", "Private transport", "Breakfast", "Fort entry tickets"],
    excluded: ["Airfare", "Lunch & dinner"],
    regions: ["Skardu", "Hunza"],
    lastUpdated: "2026-08-01",
  },
  {
    id: "pkg-04",
    slug: "10-day-complete-gb-tour",
    title: "10-Day Complete GB Grand Tour",
    category: "Luxury",
    durationDays: 10,
    images: placeholderGallery("pkg-complete-gb-10day", 4),
    estimatedPricePKR: { min: 180000, max: 260000 },
    highlights: ["Skardu", "Shigar", "Khaplu", "Hunza", "Naltar", "Gilgit", "Luxury heritage stays"],
    itinerary: [
      { day: 1, title: "Arrival in Skardu", description: "Arrive, check in to a heritage-style hotel, evening at leisure.", overnightAt: "Skardu" },
      { day: 2, title: "Skardu lakes", description: "Shangrila Lake and Kharpocho Fort.", overnightAt: "Skardu" },
      { day: 3, title: "Shigar Valley", description: "Day trip to Shigar Fort and the fertile Shigar orchards.", overnightAt: "Skardu" },
      { day: 4, title: "Khaplu Palace", description: "Drive to Khaplu, visit the restored Khaplu Palace.", overnightAt: "Khaplu" },
      { day: 5, title: "Khaplu to Skardu", description: "Return drive to Skardu with stops along the Shyok river.", overnightAt: "Skardu" },
      { day: 6, title: "Skardu to Hunza", description: "Full-day scenic drive on the Karakoram Highway.", overnightAt: "Hunza" },
      { day: 7, title: "Hunza forts & lake", description: "Baltit Fort, Altit Fort, Attabad Lake boating.", overnightAt: "Hunza" },
      { day: 8, title: "Passu & Naltar", description: "Passu Cones viewpoint, transfer towards Naltar Valley.", overnightAt: "Gilgit" },
      { day: 9, title: "Naltar lakes", description: "Day trip to Naltar's three lakes and pine forests.", overnightAt: "Gilgit" },
      { day: 10, title: "Departure", description: "Free morning in Gilgit, transfer for departure.", overnightAt: "—" },
    ],
    included: ["Heritage/luxury accommodation", "Private transport", "Breakfast & dinner", "All entry tickets"],
    excluded: ["Airfare", "Lunch", "Travel insurance"],
    regions: ["Skardu", "Shigar", "Ghanche", "Hunza", "Ghizer", "Gilgit"],
    lastUpdated: "2026-08-01",
  },
  {
    id: "pkg-05",
    slug: "honeymoon-in-hunza",
    title: "Honeymoon in Hunza",
    category: "Honeymoon",
    durationDays: 6,
    images: placeholderGallery("pkg-honeymoon-hunza", 4),
    estimatedPricePKR: { min: 110000, max: 170000 },
    highlights: ["Private mountain-view suite", "Candlelight dinner", "Attabad Lake sunset boat ride", "Couples photography walk"],
    itinerary: [
      { day: 1, title: "Arrival & welcome", description: "Private transfer to Hunza, welcome drink and check-in to a mountain-view suite.", overnightAt: "Hunza" },
      { day: 2, title: "Karimabad exploration", description: "Baltit Fort, Karimabad bazaar, sunset viewpoint together.", overnightAt: "Hunza" },
      { day: 3, title: "Attabad Lake sunset cruise", description: "Private boat ride on Attabad Lake at golden hour.", overnightAt: "Hunza" },
      { day: 4, title: "Passu day trip", description: "Suspension bridge walk and glacier viewpoint at Passu.", overnightAt: "Hunza" },
      { day: 5, title: "Leisure day & candlelight dinner", description: "Free day at the resort, private candlelight dinner in the evening.", overnightAt: "Hunza" },
      { day: 6, title: "Departure", description: "Private transfer back towards Gilgit for departure.", overnightAt: "—" },
    ],
    included: ["Luxury accommodation", "Private transport", "One candlelight dinner", "Breakfast"],
    excluded: ["Airfare", "Lunch & remaining dinners"],
    regions: ["Hunza"],
    lastUpdated: "2026-08-01",
  },
  {
    id: "pkg-06",
    slug: "family-fun-gb",
    title: "Family Fun in GB",
    category: "Family",
    durationDays: 6,
    images: placeholderGallery("pkg-family-gb", 4),
    estimatedPricePKR: { min: 100000, max: 150000 },
    highlights: ["Kid-friendly pace", "Boating", "Fort visits", "Connecting family rooms"],
    itinerary: [
      { day: 1, title: "Arrival in Skardu", description: "Arrive and settle in with an easy first day.", overnightAt: "Skardu" },
      { day: 2, title: "Shangrila Lake", description: "Relaxed boating and lakeside lunch at Shangrila.", overnightAt: "Skardu" },
      { day: 3, title: "Skardu to Hunza", description: "Scenic drive with photo stops for the kids.", overnightAt: "Hunza" },
      { day: 4, title: "Karimabad & Attabad", description: "Easy fort visit followed by boating at Attabad Lake.", overnightAt: "Hunza" },
      { day: 5, title: "Free day / optional Passu walk", description: "Optional short walk to Passu viewpoint, otherwise resort leisure time.", overnightAt: "Hunza" },
      { day: 6, title: "Departure", description: "Transfer for departure.", overnightAt: "—" },
    ],
    included: ["Family rooms", "Private transport", "Breakfast"],
    excluded: ["Airfare", "Lunch & dinner"],
    regions: ["Skardu", "Hunza"],
    lastUpdated: "2026-08-01",
  },
  {
    id: "pkg-07",
    slug: "adventure-k2-basecamp-approach",
    title: "Adventure: K2 Base Camp Approach Trek",
    category: "Adventure",
    durationDays: 12,
    images: placeholderGallery("pkg-k2-basecamp", 4),
    estimatedPricePKR: { min: 220000, max: 320000 },
    highlights: ["Baltoro Glacier", "Concordia views", "Experienced high-altitude guide", "Full trekking crew"],
    itinerary: [
      { day: 1, title: "Arrival in Skardu", description: "Arrive, gear check, permits and briefing.", overnightAt: "Skardu" },
      { day: 2, title: "Drive to Askole", description: "Jeep drive along a rugged mountain road to the trailhead village of Askole.", overnightAt: "Askole" },
      { day: 3, title: "Askole to Jhula", description: "Trek begins along the Braldu river.", overnightAt: "Camp, Jhula" },
      { day: 4, title: "Jhula to Paiju", description: "Continue upriver towards the Baltoro Glacier snout.", overnightAt: "Camp, Paiju" },
      { day: 5, title: "Rest day at Paiju", description: "Acclimatization day before the glacier trek begins.", overnightAt: "Camp, Paiju" },
      { day: 6, title: "Paiju to Khoburtse", description: "First day on the Baltoro Glacier itself.", overnightAt: "Camp, Khoburtse" },
      { day: 7, title: "Khoburtse to Concordia approach", description: "Trek deeper into the glacier with Gasherbrum and Broad Peak coming into view.", overnightAt: "Camp" },
      { day: 8, title: "Concordia — K2 Base Camp views", description: "Reach Concordia for panoramic views of K2 and the surrounding giants.", overnightAt: "Camp, Concordia" },
      { day: 9, title: "Begin descent", description: "Retrace the route down the Baltoro Glacier.", overnightAt: "Camp" },
      { day: 10, title: "Descent continues", description: "Continue the descent back towards Paiju.", overnightAt: "Camp, Paiju" },
      { day: 11, title: "Return to Askole & Skardu", description: "Trek out to Askole, jeep drive back to Skardu.", overnightAt: "Skardu" },
      { day: 12, title: "Departure", description: "Rest and transfer for departure.", overnightAt: "—" },
    ],
    included: ["Camping equipment", "Guide, cook & porters", "All meals during trek", "Permits"],
    excluded: ["Airfare", "Personal trekking gear", "Travel insurance"],
    regions: ["Skardu"],
    lastUpdated: "2026-08-01",
  },
  {
    id: "pkg-08",
    slug: "budget-backpacker-gb-circuit",
    title: "Budget Backpacker GB Circuit",
    category: "Budget Backpacker",
    durationDays: 8,
    images: placeholderGallery("pkg-backpacker-gb", 4),
    estimatedPricePKR: { min: 45000, max: 70000 },
    highlights: ["Shared transport (NATCO/vans)", "Guesthouse stays", "Flexible itinerary", "Local eateries"],
    itinerary: [
      { day: 1, title: "Arrival in Gilgit", description: "Arrive by road or air, settle into a guesthouse.", overnightAt: "Gilgit" },
      { day: 2, title: "Gilgit to Hunza", description: "Shared van to Karimabad, evening bazaar walk.", overnightAt: "Hunza" },
      { day: 3, title: "Karimabad on foot", description: "Self-guided fort and viewpoint walk.", overnightAt: "Hunza" },
      { day: 4, title: "Attabad & Passu", description: "Shared transport to Attabad Lake and Passu.", overnightAt: "Hunza" },
      { day: 5, title: "Hunza to Skardu", description: "Long scenic travel day via shared transport.", overnightAt: "Skardu" },
      { day: 6, title: "Skardu lakes", description: "Shangrila Lake and Kharpocho Fort on a budget day pass.", overnightAt: "Skardu" },
      { day: 7, title: "Deosai day trip", description: "Optional shared jeep trip to Deosai Plains.", overnightAt: "Skardu" },
      { day: 8, title: "Departure", description: "Transfer for departure.", overnightAt: "—" },
    ],
    included: ["Guesthouse stays", "Shared transport"],
    excluded: ["Airfare", "All meals", "Entry tickets"],
    regions: ["Gilgit", "Hunza", "Skardu"],
    lastUpdated: "2026-08-01",
  },
  {
    id: "pkg-09",
    slug: "luxury-hunza-skardu-retreat",
    title: "Luxury Hunza & Skardu Retreat",
    category: "Luxury",
    durationDays: 6,
    images: placeholderGallery("pkg-luxury-retreat", 4),
    estimatedPricePKR: { min: 160000, max: 240000 },
    highlights: ["5-star style resorts", "Private guide & vehicle", "Curated dining", "Priority fort access"],
    itinerary: [
      { day: 1, title: "Private arrival transfer", description: "Private vehicle transfer to a luxury resort in Skardu.", overnightAt: "Skardu" },
      { day: 2, title: "Skardu in comfort", description: "Private guided visit to Shangrila Lake and Kharpocho Fort.", overnightAt: "Skardu" },
      { day: 3, title: "Fly or drive to Hunza", description: "Scenic transfer to a premium Hunza resort.", overnightAt: "Hunza" },
      { day: 4, title: "Hunza heritage & lake", description: "Priority-access fort tours and a private Attabad Lake excursion.", overnightAt: "Hunza" },
      { day: 5, title: "Leisure & spa", description: "Free day for leisure, spa or optional Passu excursion.", overnightAt: "Hunza" },
      { day: 6, title: "Departure", description: "Private transfer for departure.", overnightAt: "—" },
    ],
    included: ["Luxury accommodation", "Private guide & vehicle", "Breakfast & dinner"],
    excluded: ["Airfare", "Lunch", "Spa treatments"],
    regions: ["Skardu", "Hunza"],
    lastUpdated: "2026-08-01",
  },
];
